# Generated by Django 5.0.1 on 2024-02-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prod',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
